name: emailtrack

services:
  backend:
    build: ./backend/EmailStatsService
    ports:
      - "5062:8080"
    networks:
      - db_net
      - email_sender_net
    depends_on:
      - db
    restart: always
  frontend:
    build: /frontend/emailtrack
    ports:
      - "3000:3000"
  db:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pa55w0rd!
    ports:
      - '1433:1433'
    expose:
      - 1433
    volumes:
      - emailtrack:/var/lib/mysql
    networks:
      - db_net

volumes:
  emailtrack:

networks:
  db_net:
    driver: bridge
  email_sender_net:
    driver: bridge